[2024-03-12T01:20:11.922-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.split_data scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-03-12T01:20:11.935-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.split_data scheduled__2024-03-11T00:00:00+00:00 [queued]>
[2024-03-12T01:20:11.936-0400] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-12T01:20:11.982-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): split_data> on 2024-03-11 00:00:00+00:00
[2024-03-12T01:20:12.007-0400] {standard_task_runner.py:60} INFO - Started process 312189 to run task
[2024-03-12T01:20:12.042-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'split_data', 'scheduled__2024-03-11T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpytgy07l5']
[2024-03-12T01:20:12.044-0400] {standard_task_runner.py:88} INFO - Job 13: Subtask split_data
[2024-03-12T01:20:13.327-0400] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.split_data scheduled__2024-03-11T00:00:00+00:00 [running]> on host DESKTOP-6U7QAQN.
[2024-03-12T01:20:13.483-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@email.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='split_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-11T00:00:00+00:00'
[2024-03-12T01:20:13.484-0400] {logging_mixin.py:188} INFO - /home/ironbong_jr/mlops/project/Group-5-Default-of-Credit-Card-Clients-IE7374/airflow/dags/dataSplit/../data/default of credit card clients.xls
[2024-03-12T01:20:13.491-0400] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'xlrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ironbong_jr/mlops/project/Group-5-Default-of-Credit-Card-Clients-IE7374/airflow/dags/dataSplit/dataSplit.py", line 11, in split
    newdata = pd.read_excel(io = sourcePath, header=1, index_col=False)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1695, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/excel/_xlrd.py", line 34, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/compat/_optional.py", line 144, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
[2024-03-12T01:20:13.515-0400] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=split_data, execution_date=20240311T000000, start_date=20240312T052011, end_date=20240312T052013
[2024-03-12T01:20:13.550-0400] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task split_data (Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.; 312189)
[2024-03-12T01:20:13.580-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T01:20:14.234-0400] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
