[2024-03-13T16:03:56.079-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_data.validate_test manual__2024-03-13T20:03:45.908970+00:00 [queued]>
[2024-03-13T16:03:56.082-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_data.validate_test manual__2024-03-13T20:03:45.908970+00:00 [queued]>
[2024-03-13T16:03:56.082-0400] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-13T16:03:56.097-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): validate_test> on 2024-03-13 20:03:45.908970+00:00
[2024-03-13T16:03:56.103-0400] {standard_task_runner.py:60} INFO - Started process 458411 to run task
[2024-03-13T16:03:56.106-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_data', 'validate_test', 'manual__2024-03-13T20:03:45.908970+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmprnedl27w']
[2024-03-13T16:03:56.106-0400] {standard_task_runner.py:88} INFO - Job 137: Subtask validate_test
[2024-03-13T16:03:56.137-0400] {task_command.py:423} INFO - Running <TaskInstance: predict_data.validate_test manual__2024-03-13T20:03:45.908970+00:00 [running]> on host DESKTOP-6U7QAQN.
[2024-03-13T16:03:56.186-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@email.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_data' AIRFLOW_CTX_TASK_ID='validate_test' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T20:03:45.908970+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T20:03:45.908970+00:00'
[2024-03-13T16:03:56.191-0400] {new_data_validate.py:25} INFO - data loaded
[2024-03-13T16:03:56.191-0400] {new_data_validate.py:29} INFO - checking for target in new data
[2024-03-13T16:03:56.269-0400] {new_data_validate.py:33} INFO - generate anomalies from new data
[2024-03-13T16:03:56.270-0400] {logging_mixin.py:188} INFO - No anomalies detected in new data
[2024-03-13T16:03:56.270-0400] {new_data_validate.py:48} INFO - No anomalies detected in new data
[2024-03-13T16:03:56.270-0400] {python.py:202} INFO - Done. Returned value was: None
[2024-03-13T16:03:56.273-0400] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=predict_data, task_id=validate_test, execution_date=20240313T200345, start_date=20240313T200356, end_date=20240313T200356
[2024-03-13T16:03:56.320-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-13T16:03:56.329-0400] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
