[2024-03-12T23:41:51.922-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_data.Train_model manual__2024-03-13T03:40:22.569579+00:00 [queued]>
[2024-03-12T23:41:51.931-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_data.Train_model manual__2024-03-13T03:40:22.569579+00:00 [queued]>
[2024-03-12T23:41:51.931-0400] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-12T23:41:51.960-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Train_model> on 2024-03-13 03:40:22.569579+00:00
[2024-03-12T23:41:51.971-0400] {standard_task_runner.py:60} INFO - Started process 421458 to run task
[2024-03-12T23:41:51.977-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'train_data', 'Train_model', 'manual__2024-03-13T03:40:22.569579+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpw1ht8yyv']
[2024-03-12T23:41:51.978-0400] {standard_task_runner.py:88} INFO - Job 106: Subtask Train_model
[2024-03-12T23:41:52.038-0400] {task_command.py:423} INFO - Running <TaskInstance: train_data.Train_model manual__2024-03-13T03:40:22.569579+00:00 [running]> on host DESKTOP-6U7QAQN.
[2024-03-12T23:41:52.149-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@email.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_data' AIRFLOW_CTX_TASK_ID='Train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T03:40:22.569579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T03:40:22.569579+00:00'
[2024-03-12T23:41:52.477-0400] {logging_mixin.py:188} INFO - [LightGBM] [Info] Number of positive: 4479, number of negative: 15771
[2024-03-12T23:41:52.482-0400] {logging_mixin.py:188} INFO - [LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001406 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[2024-03-12T23:41:52.483-0400] {logging_mixin.py:188} INFO - [LightGBM] [Info] Total Bins 3205
[2024-03-12T23:41:52.483-0400] {logging_mixin.py:188} INFO - [LightGBM] [Info] Number of data points in the train set: 20250, number of used features: 20
[2024-03-12T23:41:52.484-0400] {logging_mixin.py:188} INFO - [LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221185 -> initscore=-1.258773
[2024-03-12T23:41:52.485-0400] {logging_mixin.py:188} INFO - [LightGBM] [Info] Start training from score -1.258773
[2024-03-12T23:41:52.691-0400] {logging_mixin.py:188} INFO - [LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[2024-03-12T23:41:52.701-0400] {logging_mixin.py:188} INFO - [LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[2024-03-12T23:41:52.711-0400] {logging_mixin.py:188} INFO - model fit done
[2024-03-12T23:41:52.741-0400] {logging_mixin.py:188} INFO - model predicted
[2024-03-12T23:41:52.750-0400] {logging_mixin.py:188} INFO - 0.6677292204149451
[2024-03-12T23:41:52.757-0400] {logging_mixin.py:188} INFO - 0.8275555555555556
[2024-03-12T23:41:56.792-0400] {logging_mixin.py:188} WARNING - /home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/_distutils_hack/__init__.py:26 UserWarning: Setuptools is replacing distutils.
[2024-03-12T23:41:56.830-0400] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ironbong_jr/mlops/project/Group-5-Default-of-Credit-Card-Clients-IE7374/airflow/dags/ml/train_model.py", line 90, in train_model
    mlflow.sklearn.log_model(model, "model", signature=signature)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/sklearn/__init__.py", line 416, in log_model
    return Model.log(
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/models/model.py", line 623, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1095, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1237, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 570, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 536, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 124, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 77, in get_artifact_repository
    return repository(artifact_uri)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}
[2024-03-12T23:41:56.892-0400] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=train_data, task_id=Train_model, execution_date=20240313T034022, start_date=20240313T034151, end_date=20240313T034156
[2024-03-12T23:41:56.925-0400] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task Train_model (The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'https', 'http'}; 421458)
[2024-03-12T23:41:56.959-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T23:41:56.989-0400] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
