2024-04-24 14:31:55,585 - root - WARNING - starting a new run
2024-04-24 14:31:55,610 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:5001
2024-04-24 14:31:55,611 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/runs/get?run_uuid=e595dd0fd325478d84ea6ea4e31f2b09&run_id=e595dd0fd325478d84ea6ea4e31f2b09'): Retry(total=4, connect=4, read=5, redirect=5, status=5)
2024-04-24 14:31:55,611 - urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46f92ba080>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/get?run_uuid=e595dd0fd325478d84ea6ea4e31f2b09&run_id=e595dd0fd325478d84ea6ea4e31f2b09
2024-04-24 14:31:55,611 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 127.0.0.1:5001
2024-04-24 14:31:55,611 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/runs/get?run_uuid=e595dd0fd325478d84ea6ea4e31f2b09&run_id=e595dd0fd325478d84ea6ea4e31f2b09'): Retry(total=3, connect=3, read=5, redirect=5, status=5)
2024-04-24 14:31:59,635 - urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46f92b94e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/get?run_uuid=e595dd0fd325478d84ea6ea4e31f2b09&run_id=e595dd0fd325478d84ea6ea4e31f2b09
2024-04-24 14:31:59,637 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (3): 127.0.0.1:5001
2024-04-24 14:31:59,638 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/runs/get?run_uuid=e595dd0fd325478d84ea6ea4e31f2b09&run_id=e595dd0fd325478d84ea6ea4e31f2b09'): Retry(total=2, connect=2, read=5, redirect=5, status=5)
2024-04-24 14:32:08,411 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46f92bae00>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/runs/get?run_uuid=e595dd0fd325478d84ea6ea4e31f2b09&run_id=e595dd0fd325478d84ea6ea4e31f2b09
2024-04-24 14:32:08,412 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (4): 127.0.0.1:5001
2024-04-24 14:32:08,413 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/api/2.0/mlflow/runs/get?run_uuid=e595dd0fd325478d84ea6ea4e31f2b09&run_id=e595dd0fd325478d84ea6ea4e31f2b09'): Retry(total=1, connect=1, read=5, redirect=5, status=5)
